# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - mds-functions-william

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '22.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cleanup files and folders as per .funcignore
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force .git -ErrorAction SilentlyContinue
          Remove-Item -Force .gitignore -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force .vscode -ErrorAction SilentlyContinue
          Remove-Item -Force local.settings.json -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force test -ErrorAction SilentlyContinue
          Remove-Item -Force getting_started.md -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force node_modules/@types -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force node_modules/azure-functions-core-tools -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force node_modules/typescript -ErrorAction SilentlyContinue
          Get-ChildItem -Path . -Filter *.js.map -Recurse | Remove-Item
          Get-ChildItem -Path . -Filter *.ts -Recurse | Remove-Item

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'mds-functions-william'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FBB3EBD1E8F34E5D9E6EA4B6DF786F4E }}